cp1=int(input())
np1=int(input())
vp1=float(input())
cp2=int(input())
np2=int(input())
vp2=float(input())
total=(np1*vp1)+(np2*vp2)
print(f"VALOR A PAGAR: R$ {total:.2f}")
lista1 = input().strip()
valores1 = lista1.split()
cp1, np1, vp1 = int(valores1[0]), int(valores1[1]), float(valores1[2])
lista2 = input().strip()
valores2 = lista2.split() 
cp2, np2, vp2 = int(valores2[0]), int(valores2[1]), float(valores2[2])